services:
  db:
    image: postgres:16-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: xunbao_user
      POSTGRES_PASSWORD: xunbao_password
      POSTGRES_DB: xunbao_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
